title: AROLUMI
description: 环绕的思绪与微光的记录
author: light
theme: minima

# 可选：自动深浅色
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: https://github.com/你的用户名 }

plugins:
  - jekyll-feed
